### ISSUE TITLE
0.5.3 只能点首页的内容 搜索栏输入后回车没反应

### ISSUE THREAD

**Issue by lifangzheng** [iTVSeries/iTVSeries#2]
0.5.3 只能点首页的内容 搜索栏输入后回车没反应

**Comment by lifangzheng** [comment]
系统 10.10.3

**Comment by iTVSeries** [comment]
@lifangzheng 这是因为现在搜索做的比较简陋，没有搜索状态显示(错误，无数据等)，另外可以试一下用英文剧名搜索，或者你可以提供一下检索字，我这边搜索一下

**Comment by lifangzheng** [comment]
@iTVSeries 如图 搜暴君或者tyrant没响应
![2016-02-13 2 17 16](https://cloud.githubusercontent.com/assets/12532311/13016171/1f9d5fe6-d1f8-11e5-8d69-4137c9cf5003.png)
![2016-02-13 2 17 16](https://cloud.githubusercontent.com/assets/12532311/13016172/20974ff6-d1f8-11e5-9ad1-6a5e17b930bb.png)
但是搜单个字母t就有反应
![2016-02-13 2 17 59](https://cloud.githubusercontent.com/assets/12532311/13016183/2e17abe4-d1f8-11e5-977e-abba42fdc569.png)
![2016-02-13 2 17 47](https://cloud.githubusercontent.com/assets/12532311/13016186/2f3261fe-d1f8-11e5-81e3-68435eb941d9.png)

**Comment by tasselx** [comment]
@lifangzheng 我这边是抓取的接口，刚测试了下是搜不到你需要检索的数据的，无反应是我这边没做无数据状态显示，下个版本会加上的

**Comment by lifangzheng** [comment]
感谢！
