### ISSUE TITLE
很不理解，画质问题

### ISSUE THREAD

**Issue by peterzhangnull** [iTVSeries/iTVSeries#5]
无论选择原画还是超清都是一个样子，看了解析的原视频本身就是质量高的，结果到这里就成马赛克画质

**Comment by Frank-Heisenway** [comment]
确实，画质不行啊

**Comment by tasselx** [comment]
@zhangyenull @Frank-Heisenway 一个人精力有限，画质不是个人能够控制的，加之现在存在的一些问题，iTVSeries停止更新维护，感谢关注

**Comment by Gail9527** [comment]
能否把以前的代码开源出来呢
