### ISSUE TITLE
每一个都地址解析错误，下载和播放都是

### ISSUE THREAD

**Issue by phpmaple** [iTVSeries/iTVSeries#6]
我自己安装过 Aria，不知道是不是这个原因

**Comment by chenxi0324** [comment]
一样的问题，看到提示，貌似作者这个是调用的各种视频的API做的整合，然后boom。。。 我在Apple TV3上使用dns解析的时候，采用类似离线百度云盘的形式亦可做到在线播放，不知道作者是否考虑这种模式的可行性

**Comment by tasselx** [comment]
@phpmaple @chenxi0324 感谢关注，非常抱歉，由于一些原因iTVSeries现已停止更新维护
